//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookService
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class OnCard
    {
        [DataMember]
        public int Quantity { get; set; }
        [DataMember]
        public int BookId { get; set; }

        [DataMember]
        public virtual Book Book { get; set; }
    }
}
