//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messaging
    {
        public int UserID { get; set; }
        public int CompanyID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime Time { get; set; }
        public string Sender { get; set; }
    }
}
