//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/SimpleService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Genre {
            get {
                return this.GenreField;
            }
            set {
                if ((object.ReferenceEquals(this.GenreField, value) != true)) {
                    this.GenreField = value;
                    this.RaisePropertyChanged("Genre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBookShop")]
    public interface IBookShop {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooks", ReplyAction="http://tempuri.org/IBookShop/GetBooksResponse")]
        BookStore.ServiceReference1.Book[] GetBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooks", ReplyAction="http://tempuri.org/IBookShop/GetBooksResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBookByID", ReplyAction="http://tempuri.org/IBookShop/GetBookByIDResponse")]
        BookStore.ServiceReference1.Book[] GetBookByID(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBookByID", ReplyAction="http://tempuri.org/IBookShop/GetBookByIDResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBookByIDAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByAuthor", ReplyAction="http://tempuri.org/IBookShop/GetBooksByAuthorResponse")]
        BookStore.ServiceReference1.Book[] GetBooksByAuthor(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByAuthor", ReplyAction="http://tempuri.org/IBookShop/GetBooksByAuthorResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByAuthorAsync(string author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByName", ReplyAction="http://tempuri.org/IBookShop/GetBooksByNameResponse")]
        BookStore.ServiceReference1.Book[] GetBooksByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByName", ReplyAction="http://tempuri.org/IBookShop/GetBooksByNameResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByGenre", ReplyAction="http://tempuri.org/IBookShop/GetBooksByGenreResponse")]
        BookStore.ServiceReference1.Book[] GetBooksByGenre(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByGenre", ReplyAction="http://tempuri.org/IBookShop/GetBooksByGenreResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByGenreAsync(string genre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByPrice", ReplyAction="http://tempuri.org/IBookShop/GetBooksByPriceResponse")]
        BookStore.ServiceReference1.Book[] GetBooksByPrice(string price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/GetBooksByPrice", ReplyAction="http://tempuri.org/IBookShop/GetBooksByPriceResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByPriceAsync(string price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/Search", ReplyAction="http://tempuri.org/IBookShop/SearchResponse")]
        BookStore.ServiceReference1.Book[] Search(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookShop/Search", ReplyAction="http://tempuri.org/IBookShop/SearchResponse")]
        System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> SearchAsync(string value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookShopChannel : BookStore.ServiceReference1.IBookShop, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookShopClient : System.ServiceModel.ClientBase<BookStore.ServiceReference1.IBookShop>, BookStore.ServiceReference1.IBookShop {
        
        public BookShopClient() {
        }
        
        public BookShopClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookShopClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookShopClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookShopClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookStore.ServiceReference1.Book[] GetBooks() {
            return base.Channel.GetBooks();
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksAsync() {
            return base.Channel.GetBooksAsync();
        }
        
        public BookStore.ServiceReference1.Book[] GetBookByID(string id) {
            return base.Channel.GetBookByID(id);
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBookByIDAsync(string id) {
            return base.Channel.GetBookByIDAsync(id);
        }
        
        public BookStore.ServiceReference1.Book[] GetBooksByAuthor(string author) {
            return base.Channel.GetBooksByAuthor(author);
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByAuthorAsync(string author) {
            return base.Channel.GetBooksByAuthorAsync(author);
        }
        
        public BookStore.ServiceReference1.Book[] GetBooksByName(string name) {
            return base.Channel.GetBooksByName(name);
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByNameAsync(string name) {
            return base.Channel.GetBooksByNameAsync(name);
        }
        
        public BookStore.ServiceReference1.Book[] GetBooksByGenre(string genre) {
            return base.Channel.GetBooksByGenre(genre);
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByGenreAsync(string genre) {
            return base.Channel.GetBooksByGenreAsync(genre);
        }
        
        public BookStore.ServiceReference1.Book[] GetBooksByPrice(string price) {
            return base.Channel.GetBooksByPrice(price);
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> GetBooksByPriceAsync(string price) {
            return base.Channel.GetBooksByPriceAsync(price);
        }
        
        public BookStore.ServiceReference1.Book[] Search(string value) {
            return base.Channel.Search(value);
        }
        
        public System.Threading.Tasks.Task<BookStore.ServiceReference1.Book[]> SearchAsync(string value) {
            return base.Channel.SearchAsync(value);
        }
    }
}
